---
- name: Add awx group
  group: name={{ awx_group }} gid={{ awx_gid }} state=present

- name: Add awx user
  user: name={{ awx_group }} uid={{ awx_uid }} group={{ awx_group }} system=yes state=present

- name: Copy ssh public key
  copy:
    src: awx_id_rsa.pub
    dest: "~{{ awx_user }}/.ssh/authorized_keys"
    user: "{{ awx_user }}"
    group: "{{ awx_group }}"
    mode: "0600"

- name: Configure AWX user for SUDO access
  template:
    src: "awx.sudoers.d.j2"
    dest: "/etc/sudoers.d/awx"
    user: "root"
    group: "{{ awx_group }}"
    mode: "0640"
